### ISSUE TITLE
Compatability with Lotus::Model/Entity

### ISSUE THREAD

**Issue by plukevdh** [lotus/validations#52]
Seeing consistency break down when including/using validations with `Lotus::Model`'s `Entity` mixin. The interface to a defined entity changes subtly so as to break expectations. See the following example:

```ruby
class DummyModel
  include Lotus::Entity
  attributes :name, :email
end
# => [:name, :email]

DummyModel.attributes
# => #<Set: {:id, :name, :email}>

m = DummyModel.new name: "Luke", email: "test@me.com"
# => #<DummyModel:0x007fdc8d135b48 @email="test@me.com", @name="Luke">

m.to_h
# => {:id=>nil, :name=>"Luke", :email=>"test@me.com"}
```

Vs the output of:

```ruby
class OtherModel
  include Lotus::Entity
  include Lotus::Validations
  attribute :email, presence: true
  attribute :name, presence: true
end
#=> [:name]

OtherModel.attributes
#=> #<Set: {:id, :email, :name}>
# Note, attributes includes the id here...

o = OtherModel.new name: "Luke", email: "test@me.com"
#=> #<OtherModel:0x007fc03ba9c1f0 @attributes=#<Lotus::Utils::Attributes:0x007fc03ba9c1c8 @attributes={"name"=>"Luke", "email"=>"test@me.com"}>>
# The internal structure (or at least the output of the inspect method) has changed

o.to_h
#=> {:email=>"test@me.com", :name=>"Luke"}
# What happened to the id field? `.attributes` tells me I should be able to expect it returned...
```

I can note that if I specify `attribute :id` at the same time as the validators, I can get it to return the id as well, but this is not consistent with how Lotus::Model acts.

**Comment by plukevdh** [comment]
One more note, that is more confusing as the docs indicate this ought to work:

```ruby
class OneMore
  include Lotus::Entity
  include Lotus::Validations
  attributes :name, :email
  validates :email, presence: true
end
# => nil

OneMore.attributes
# => #<Set: {:id, :name, :email}>

m = OneMore.new name: "Luke", email: "test@me.com"
# => #<OneMore:0x007fc03bba6ff0 @attributes=#<Lotus::Utils::Attributes:0x007fc03bba6fc8 @attributes={"email"=>"test@me.com"}>>

m.to_h
# => {:email=>"test@me.com"}
```

**Comment by jodosha** [comment]
@plukevdh Hello and thanks for sharing this problem. It absolutely deserves a fix. My plans were to include it with 0.3.0, but the release date is tomorrow, and we don't have enough time to do it now.

I tried to write a patch on the fly, but it deserves a better investigation. I hope it won't be a problem if we postpone the fix a bit. Thank you :smile:

**Comment by jodosha** [comment]
@plukevdh Would you mind to check if the PR above fixes your issue? Thank you!

**Comment by plukevdh** [comment]
Can do. Sorry for the delay. I'll update here as soon as I have a chance to run.

**Comment by jodosha** [comment]
@plukevdh We've merged that fixing PR because it looks good. Feel free to reopen this ticket if still doesn't work for you. Thanks.
