### ISSUE TITLE
Default values for attributes?

### ISSUE THREAD

**Issue by PaBLoX-CL** [lotus/validations#54]
I was using `lotus/validations` in my gem, I liked the syntax sugar of attribute, with their validations. But I found out that there's no way to include default data. It seems (to me at least) something basic, so maybe I'm just missing something obvious (I read the verbose explanation on how to use only the validations, but using that I have to sacrifice almost all the sugar).

Is there already a way to do it?

**Comment by AlfonsoUceda** [comment]
@PaBLoX-CL could you provide an example where the default options is useful?

**Comment by PaBLoX-CL** [comment]
Sure, thought I believe I didn't explain it too well :/, hopefully it will be clearer after the example:

```ruby
class Character
  include Lotus::Validations

  attribute :name, presence: true
  attribute :race, presence: true
  attribute :age, type: Integer
  attribute :level, default: 1
  
end
> Character.new(name: 'Legolas', race: 'elf')
#<Character:0x007f5feaf6adc8 @attributes=#<Lotus::Utils::Attributes:0x007f5feaf6ada0 @attributes={"name"=>"Legolas", "race"=>"elf", "level"=>1}>>
```

I basically meant to create default values when instantiating the class.

Right now, I'm using this:

```ruby
class Character
  include Lotus::Validations

  attribute :name, presence: true
  attribute :race, presence: true
  attribute :age, type: Integer
  attribute :level
  
  def initialize chars = {}
    chars[:level] = 1 unless chars[:level]
    super(chars)
  end
end
```

**Comment by AlfonsoUceda** [comment]
I think is useful provide default values, what do you think @jodosha @joneslee85

**Comment by jodosha** [comment]
@PaBLoX-CL Hello and thanks for starting this discussion.
I see validations like a way to deal with user input for a specific use case, [not to build models](http://lucaguidi.com/2014/10/23/introducing-lotus-validations.html). In your example, you're clearly using validations to define a business rule.

I'm not sure if this proposal is a good idea, but I'm here to listen. Would you mind to expand a little bit your use case? How often did you had to override `#initialize`? Is that painful to override `#level` in this way?

```ruby
DEFAULT_LEVEL = 1

def level
  super || DEFAULT_LEVEL
end
```

**Comment by PaBLoX-CL** [comment]
I totally understand your point and I agree with it.

The problem is that in my case, I'm just requiring lotus validations, and that specific macro (`attribute`), creates the setter and the getter method. In fact, the object created belongs to `Attributes::Utils` (at least in the example above).  I was not actually speaking about building models...

Oh, and no, it's not that painful at all, we programmers are lazy :P

**Comment by jodosha** [comment]
> Oh, and no, it's not that painful at all, we programmers are lazy :P

You made me smile :smile:

When I present Lotus at conferences, I always give this example. Think of a coffee machine that satisfies your laziness with its convenience: you push a button and it gives you an average coffee. Then think about an Aeropress, it requires a little bit of effort from you, but it's simple and the coffee is great.

The latter is the usage that you should expect when build stuff with Lotus. Avoiding this feature helps the internals of this gem to be simple and then fast. You still have to define your method, but it's not a big price to pay in the end.

I'm closing this, thank you. :coffee:
