### ISSUE TITLE
Extracting nested attributes values as a nested hash

### ISSUE THREAD

**Issue by danelowe** [lotus/validations#58]
I guess this may be expected behaviour, but thought I'd raise it as I've come against it a few times when trying to use Lotus::Validations to create form objects.

Given a Form Object e.g. 

```ruby 
module Admin::Forms
  module Job
    class Search
      include Lotus::Validations
      attribute :filter do
        attribute :id,              type: String
        attribute :customer_name,   type: String
        attribute :customer_email,  type: String
        attribute :vendor_name,     type: String
        attribute :state,           type: String
      end
    end
  end
end
```

Running the following

```ruby
form = Admin::Forms::Job::Search.new(filter: {customer_name: 'Buster'})
form.to_h
```

Nets 

`{:filter=>#<#<Class:0x007fb4fab8de70>:0x007fb4f9629908 @attributes=#<Lotus::Utils::Attributes:0x007fb4fac25658 @attributes={\"customer_name\"=>\"Buster\"}>>}`

This output is quite hard to use again to do something such as initialise a new object or merge the new data with a hash. I've ended up creating methods to iteratively cast the nested attributes as hashes before using the output. 

Wondering if is worth looking into?

**Comment by jodosha** [comment]
@danelowe Hello, I'm sorry about this poor experience. I've just merged a PR that fixes this problem

In your case, it will return:

```ruby
form = Admin::Forms::Job::Search.new(filter: {customer_name: 'Buster'})
form.to_h # => { :filter => { :customer_name => "Buster" }}
```

Please let me know if it still doesn't work for you. Thanks.

**Comment by danelowe** [comment]
Hey @jodosha Thanks so much for looking into this. It seems to work, but it also seems another regression may have been introduced? 

```ruby
require 'lotus/validations'
class Form
  include Lotus::Validations
  attribute :tags, type: Array
end
form = Form.new(tags: [:te, :st])
form.to_h
```

`lib/lotus/utils/hash.rb:31:in 'to_h': wrong element type Symbol at 0 (expected array) (TypeError)`

I guess it comes from Lotus::Utils::Attributes#_read_attribute.

If the value is an array, it responds to to_h, but will raise an error unless the array happens to be in the right 'format' for converting to a hash.

**Comment by jodosha** [comment]
@danelowe Sorry, you're right. :crying_cat_face: That's because latest versions of Ruby have introduced `Array#to_h`. Fix is on the way.

**Comment by jodosha** [comment]
@danelowe Can you please try again with master? Thank you and sorry again for the troubles.

**Comment by danelowe** [comment]
@jodosha My tests are now passing :tada: thanks!
