### ISSUE TITLE
[Question] Validation Object receiving key arguments as string

### ISSUE THREAD

**Issue by hlegius** [lotus/validations#75]
I was playing with Validations within a Rails app when got something interesting:

```ruby
class FooController
  def create
    # params = {title: => ‘Awesome Task’, due_date: => ‘2015-10-20’, non_used_param: => ‘I am garbage!'}
    task_validation = TaskValidation.new(params)
    task_validation.valid? # < = true

    # params = {‘title’ => ‘Awesome Task’, ‘due_date’ => ‘2015-10-20’, ‘non_used_param’ => ‘I am garbage!'}
    task_validation = TaskValidation.new(params)
    task_validation.valid? # <= false
    task_validation.errors # <= #<Lotus::Validations::Errors:0x007ff86b86b1c0 @errors={}>
  end
end

class TaskValidation
  include Lotus::Validations

  attribute :title
  attribute :due_date

  validates :title, presence: true
end
```

In other words: if my `params` has keys as symbol, it works fine; if keys are strings, won't work and also, `.errors` returns an empty `@errors`.

I don't know if is an expected behavior or a non-implemented and could be a feature to be added.

Any thoughts?
Thanks in advance!

**Comment by hlegius** [comment]
Investigating this in depth I've found that this error raises only when `params` is an `ActiveController::Parameter` class. This isn't a bug itself, IMO, just a case of implicit casting from Rails class into hash (params). If `params` got converted into hash before pass it to Lotus Validator class, everything works fine.

**Comment by jodosha** [comment]
@hlegius Hello :smile: To guarantee compatibility with other libs, we [internally coerce](https://github.com/lotus/validations/blob/master/lib/lotus/validations/attribute_definer.rb#L513) to `Hash`.

Now, because you have decoupled attributes definition from validation rules, I guess that mechanism is circumvented. Can you please try if:

  1. That coercion happens
  2. If you merge attributes and validations if it works fine (eg. `attribute :title, presence: true`)

Thanks :dog:

**Comment by hlegius** [comment]
@jodosha I've modified to "one line" mode as follows:

```ruby
class TaskValidation
  include Lotus::Validations

  attribute :title, presence: true, size: 8..40
  attribute :due_date, type: Date
end
```

but, it didn't work. Same problem. I've debugged a bit and found this:

![screen shot 2015-10-21 at 09 29 34](https://cloud.githubusercontent.com/assets/36469/10635281/56519f6a-77d6-11e5-937d-b4a614980a2c.png)

Running it within Rails Controller, before Lotus Validation has called, I've got the same

![screen shot 2015-10-21 at 09 34 37](https://cloud.githubusercontent.com/assets/36469/10635373/0b7327a6-77d7-11e5-8974-f05d0881f8c0.png)

Both `:title` and `:due_date` are described in routes config. So, looks like is something outside Lotus Validation, so I will close the "issue".

Thanks! :dancers:

**Comment by jodosha** [comment]
@hlegius Thanks for the update. Is that probably related to ActionController Strong Parameters. IIRC they whitelist params too.

**Comment by AlexanderMint** [comment]
How to make so there would be no mistake if a key - a string?

``` ruby
require 'hanami-validations'
class Signup
  include Hanami::Validations

  validations do
    required(:name) { filled? }
  end
end

Signup.new('name' => 'Luca').validate.errors # Error: {:name=>["is missing"]}
Signup.new(name: 'Luca').validate.errors # {}
```
