### ISSUE TITLE
param not required is still validated

### ISSUE THREAD

**Issue by caspg** [lotus/validations#77]
In controller I have following code:
```ruby
params do
  param :path, format: /^\S+$/
end
```

Sending request without `:path` param, in fact sends an empty `:path`:

`params.to_h` returns `{ "path"=>"" }` 

Validation fails due to format constraint.

**Comment by caspg** [comment]
Since we can get an empty string (but we don't want to check if this param is present), we could use for example `#blank_value?` method and change:
https://github.com/lotus/validations/blob/master/lib/lotus/validations/attribute.rb#L213-L215
```ruby
def skip?
  @value.nil?
end
```
to:
```ruby
def skip?
  blank_value?
end
```

@jodosha  What do you think?

**Comment by joneslee85** [comment]
@caspg thanks for the bug report, can you verify if this also the case for using lotus/validation alone with other framework?

**Comment by caspg** [comment]
@joneslee85 I'm not sure how can I use lotus/validation for params in other frameworks. But sinatra and rails, also return empty string ("") as a param, when you submit empty input. So I believe that problem will be the same. That's why I think we should check in `skip?` method if value is nil or empty string.

**Comment by jodosha** [comment]
@caspg Thanks for reporting this issue :+1: 

That strategy that involves "blank" fixes your problem, but creates a new one.

```ruby
class SizeValidator
  include Lotus::Attributes
  attribute :tags, size: 3
end

SizeValidator.new.valid? # => true - OK
SizeValidator.new(tags: []).valid? # => true - OUCH
```

But you give us a great hint :sparkles:

Please check if the attached PR fixes your case.

**Comment by caspg** [comment]
@jodosha With PR it works great, thanks :smiley:

**Comment by jodosha** [comment]
@caspg :tophat:
