### ISSUE TITLE
Empty parameter values with defined size attribute are not valid 

### ISSUE THREAD

**Issue by hlegius** [lotus/validations#81]
Hello there!

I've found a bug within `size` and blank values. If I define `size` attribute and try to pass the attribute as blank/empty, it will fail.

```ruby
class User
  attribute :name, size: 8..10
end

User.new({name: '', other: 'foo'}).valid? # <= false
User.new({name: '12345678', other: 'foo'}).valid? # <= true
User.new({other: 'foo'}).valid? # <= true
```

```ruby
class User
  attribute :name
  attribute :other, size: 2..10
end

User.new({name: '', other: 'foo'}).valid? # <= true
```

How should it be, IMO:

```ruby
class User
  attribute :name, size: 3..10
  attribute :other_param, presence: true, size: 2..10
end

User.new({name: '', other_param: 'abc'}).valid? # <= true
User.new({name: 'a', other_param: 'abc'}).valid? # <= false
User.new({name: 'abc', other_param: 'abc'}).valid? # <= true
User.new({name: 'abc'}).valid? # <= false
User.new({other_param: 'abc'}).valid? # <= true
```

If you guys agrees, I'd like to fix it :+1:

**Comment by jodosha** [comment]
@hlegius Please fix it. I guess this problem was introduced by myself with this commit: https://github.com/lotus/validations/commit/f0b90201bfba9947744703c0e9313be5080eb785

Can you please verify and find a solution for both the issues? Thank you very much! :100:

**Comment by hlegius** [comment]
@jodosha sure! :+1:
