### ISSUE TITLE
Clarification on truthiness of empty string for acceptance validation

### ISSUE THREAD

**Issue by Lytol** [lotus/validations#84]
The [README](https://github.com/lotus/validations/blob/master/README.md) gives an example of the empty string evaluating to `false` for truthiness on acceptance validation:

    signup = Signup.new(terms_of_service: '')
    signup.valid? # => false

However, it currently evaluates to `true` (see <https://github.com/lotus/utils/blob/master/lib/lotus/utils/kernel.rb#L911>). I'm happy to submit a PR, but need to know which is the intended behavior.

**Comment by AlfonsoUceda** [comment]
Hi @Lytol I was testing the message and it evaluates to false against master and 0.4.x branches

**Comment by Lytol** [comment]
I added a failing test to indicate: <https://github.com/lotus/validations/compare/master...Lytol:bug_empty_string_acceptance>

**Comment by pascalbetz** [comment]
@Lytol i created a PR for this. Only after i already coded the test + fix i found this issue. Sorry.

https://github.com/lotus/validations/pull/85

@AlfonsoUceda there are various examples in the code and at least one lists empty string as "false".

This seems to be wrong: https://github.com/lotus/validations/blob/master/lib/lotus/validations/attribute_definer.rb#L79 as ruby truthiness does not include ```"0"``` which is in the test at https://github.com/lotus/validations/blob/master/test/acceptance_validation_test.rb#L23

According to this: https://github.com/lotus/validations/blob/master/lib/lotus/validations/attribute_definer.rb#L162 empty string should be false.

**Comment by jodosha** [comment]
Fixed by #85 Thanks to @pascalbetz
