### ISSUE TITLE
Validator for `size_at_least`

### ISSUE THREAD

**Issue by cllns** [lotus/validations#86]
Right now, if you want to validate a size is greater than a value, (it seems) you have to pick an arbitrary upper-bound for the Range.
```
attribute :text, presence: true, size: 5..99
```

In most cases this will be fine. But let's say you want to make sure a blog post is at least 5 characters long, and during development you pick an arbitrary upper-bound of 1000, let's say. It could be a while before you realize that you're limiting the size of the blog text.

Instead, it'd be better if you could do:

```
attribute :text, presence: true, size_at_least: 5
```

(Another name could be `size_greater_than`)

Note: `size_at_most` / `size_less_than` is less important, since it can be handled with a Range starting at 0. It'd probably make sense to implement though, to be consistent.

I'd be happy to implement it, if this is something we want to do!

**Comment by joneslee85** [comment]
IMO, I would not add more complex predicates into lotus/validation anymore.

I think for such case you could do a custom proc/lambda way.

**Comment by jodosha** [comment]
@cllns I agree with @joneslee85 

You can still obtain that validation logic with `:size`. It hasn't that **exact** semantic of `:size_at_most`, but these cases should be handled by custom validations, not by other DSLish options. :wink:
